### ISSUE TITLE
Piano Roll Undetected (Live 10.1.9)

### ISSUE THREAD

**Issue by ZainM0** [Inversil/LESwin#4]
LES 1.3 does not auto detect Live's piano roll at all. ( However Scales menu works if LES 1.2 is used). 
Some users reported that LES fails to open the scales menu once or twice ( which is fine) but it doesn't open the Scales menu for me at all. 

Using Live 10.1.9 ( in Win 1809 ) right now , been using LES for a long time , without any issue until LES 1.3
(PS. I 💜 LES)

**Comment by Inversil** [comment]
yeah, I know about this. The piano roll detection just checks a few random sections of your screen to try find the piano graphic. sometimes if you resize the piano roll it it will catch it again, but the best failproof way to do this is to just use the manual piano menu mode with the shift key.

This is mostly just because of limitations with AHK and ableton. You can adjust the area of the screen it checks and how often in the source code until you get something that better matches your setup, but I don't think it's worth it. There's unfortunately no more fool-proof way to detect this without integrating with max.
